import {test} from 'node:test';
import assert from 'node:assert/strict';
import {publicIP,validateURL,safeRequest} from '../src/network.js';
test('well-known NAT64 preserves the embedded IPv4 boundary',()=>{assert.equal(publicIP('64:ff9b::14c8:f5f5'),true);for(const ip of ['64:ff9b::7f00:1','64:ff9b::a00:1','64:ff9b::a9fe:a9fe','64:ff9b:1::14c8:f5f5'])assert.equal(publicIP(ip),false,ip);});
import {validateInput,stepsFor,validatePlan} from '../src/contracts.js';
test('private, metadata, mapped and reserved addresses cannot enter URL fetcher',()=>{for(const ip of ['127.0.0.1','10.0.0.1','169.254.169.254','172.16.2.1','192.168.1.1','100.64.1.1','0.0.0.0','224.1.1.1','::1','::ffff:127.0.0.1','fe80::1','fc00::1','2001:db8::1'])assert.equal(publicIP(ip),false,ip);assert.equal(publicIP('1.1.1.1'),true);assert.equal(publicIP('2606:4700:4700::1111'),true);for(const url of ['http://127.1','http://2130706433','http://[::1]','http://user:pass@example.com','file:///etc/passwd','http://localhost','http://example.com:0','http://127.0.0.1:8088','https://example.com:65536'])assert.throws(()=>validateURL(url));});
test('destination scope rejects a different origin before DNS or credential transmission',async()=>{await assert.rejects(safeRequest('https://example.com',{allowedOrigin:'https://api.example.org'}),/허용되지/);});
test('input contract preserves false, zero, empty values and file metadata',()=>{const fields=[{name:'n',label:'n',type:'number',required:true},{name:'b',label:'b',type:'boolean',required:true},{name:'s',label:'s',type:'text',required:false}];assert.deepEqual(validateInput(fields,{n:0,b:false,s:''}),{n:0,b:false,s:''});assert.throws(()=>validateInput(fields,{n:'bad',b:false}),/숫자/);assert.throws(()=>validateInput(fields,{b:false}),/입력/);});
test('progress plan contains only actual dependencies and final step is pending',()=>{const plain=stepsFor({auth:{kind:'none'},database:{kind:'none'},hasUI:true});assert.equal(plain.length,6);assert.equal(plain.at(-1).status,'pending');const extra=stepsFor({auth:{kind:'bearer'},database:{kind:'postgres'},hasUI:false});assert.equal(extra.length,9);assert.equal(extra[0].status,'completed');});
